### ISSUE TITLE
[Question] Why do I have higher FPS with ray tracing than rasterization ?

### ISSUE THREAD

**Issue by Mafo369** [nvpro-samples/vk_shaded_gltfscene#1]
I'm using an NVIDIA RTX 3090 and Intel i9-10900X CPU and I don't understand how can I have higher FPS with ray tracing.

Using the FPS and frame generation time on the top I average around 1000 FPS / 0.9ms using ray tracing, but in raster I get around 430 FPS / 2.3ms without any super sampling multiplier (ie. no AA).

Also I tried using my own timer for the raster and ray tracing function and I get around ~0.2ms for ray tracing, and ~0.4ms for raster.

For reference here are my scene stats:
Instances: 120
Mesh: 120
Materials: 99
Triangles: 7858115
Lights: 0
Textures: 104
Images: 68
4k environment map.

**Comment by droettger** [comment]
Rasterizers get slower with the number of primitives and the amount of overdraw (shading pixels which aren't actually visible inside the final image because another triangle was in front).

Ray tracing instead is scaling with the number of rays, not so much with the number of primitives, because those are stored inside an acceleration structure which is used to quickly find the closest hit and only shade that.
Especially with instancing, which can result in huge amounts of primitives on screen, ray tracers will outperform rasterizers easily. For example: https://blogs.nvidia.com/blog/2019/04/26/first-commercial-renderer-with-nvidia-rtx-ray-tracing/

**Comment by Mafo369** [comment]
Thanks for the response ! It makes sense now.
